Repository wbhoomika/python4beginners-Hacktoberfest21, pull requests merged in 2021-10, with the labels that each got.

#5 palindrome program and changed CONTRIBUTING.md
  CONTRIBUTING.md
  checkPalindromeNumber.py
Labels: hacktoberfest-accepted

#6 Add files via upload
  Rearrange the array in alternating positive and negative items with O(1) extra space.py
Labels: hacktoberfest-accepted

#7 Added Python scripts for the game TicTacToe and the number guessing game
  guessTheNumber.py
  tictactoe.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#8 display permutation/combination of string
  CONTRIBUTING.md
  PermutationOfStringFromInput.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#9 A guide to loops in python
  CONTRIBUTING.md
  for_loop.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#10 learning open sources....
  CONTRIBUTING.md
  Prim's_algorithm.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#11 Functions in Python.
  CONTRIBUTING.md
  funktions.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#12 Leapyear.py
  CONTRIBUTING.md
  Leapyear.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#13 ADD: File for HacktoberFest
  CONTRIBUTING.md
  numpy_basic.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#14 Add files
  CONTRIBUTING.md
  find_gcd.py
  infix_to_postifx.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#15 linked_lists.py
  CONTRIBUTING.md
  linked_lists.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#16 Added code for Bubble sort
  Bubble Sort.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#18 Factorial.py
  Factorial.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#20 Create ZigZagPattern.py
  ZigZagPattern.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#21 Added Calculator Tkinter Program
  calculator.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#22 Create students_info.py
  students_info.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#24 Create twoSum.py
  twoSum.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#25 Snake Game in python
  Python Codes/Snake Game.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#27 Created Fibonacci.py
  Python Codes/Fibonacci.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#30 Area.py
  Area.py
Labels: invalid, wontwork, Hacktoberfest

#33 Print First and Last element in array using List indexing.py
  Python Codes/Print First and Last element in array using List indexing.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#32 Added Sorting Programs using Python
  Python Codes/Advance Python/Sorting Program/Bubblesort.py
  Python Codes/Advance Python/Sorting Program/Insertionsort.py
  Python Codes/Advance Python/Sorting Program/Mergesort.py
  Python Codes/Advance Python/Sorting Program/Selectionsort.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#34 Python program to block the external website
  Python Codes/Blocking_website.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#35 Create scan.py
  Python Codes/scan.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#37 Add 'Mail Merge' Python Project in Advance Python
  .DS_Store
  CONTRIBUTING.md
  Python Codes/.DS_Store
  Python Codes/Advance Python/.DS_Store
  Python Codes/Advance Python/Mail Merge Python/.DS_Store
  Python Codes/Advance Python/Mail Merge Python/Input/.DS_Store
  Python Codes/Advance Python/Mail Merge Python/Input/Letters/starting_letter.txt
  Python Codes/Advance Python/Mail Merge Python/Input/Names/invited_names.txt
  Python Codes/Advance Python/Mail Merge Python/Output/.DS_Store
  Python Codes/Advance Python/Mail Merge Python/Output/ReadyToSend/example.txt
  Python Codes/Advance Python/Mail Merge Python/main.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#38 Solved questions DSA from Leetcode
  Python Codes/Advance Python/Solved_leetcode_part1.ipynb
  Python Codes/Advance Python/Solved_leetcode_part2.ipynb
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#41 Create BreadthFirstSearch
  Python Codes/BreadthFirstSearch
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#42 Calendar.py
  Python Codes/Calendar.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#43 List indexing in Python
  Python Codes/Grabbing first and last element of an Array/List using List Indexing in python.
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#44 Updated repository
  Python Codes/22.Generators.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#45 Create quickSort.py
  Python Codes/Advance Python/Sorting Program/quickSort.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#57 bert model for political divergence
  Python Codes/bert.ipynb
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#51 Create naeema19_probdiff.py
  Python Codes/naeema19_probdiff.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#52 A virtually created fidjet spinner
  Python Codes/main.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#53 Added program for unblocking the website
  Python Codes/Unblocking_website.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#55 Code for Harry Potter's Invisiblity Cloak
  CONTRIBUTING.md
  Python Codes/Advance Python/Magic_Cloak.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#56 added a program to print prime numbers in a given range
  CONTRIBUTING.md
  Python Codes/primeNumberGenerator.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#61 factors_number.py
  Python Codes/factors_number.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#63 Added reverse_integer
  Python Codes/reverse_integer.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#64 Sudoku_Game_Solver
  CONTRIBUTING.md
  Python Codes/sudoku game solver.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#68 LDA topic modelling.
  US Topic modelling.ipynb
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#71 Added Matrix Multiplication
  Python Codes/matrix_multiplication.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#72 Create Face_recognition.py
  Python Codes/Face_recognition.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#73 add prims algorithm
  Python Codes/primsalgorithm.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#76 Add files via upload
  Python Codes/chopstick_game.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#184 image2sketch
  Python Codes/Image to Pencil Sketch/Readme.md
  Python Codes/Image to Pencil Sketch/img2sketch.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#185 Create screenrecorder.py
  Python Codes/screenrecorder.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#186 Created Dice Rolling Simulator
  Python Codes/dice_rolller_simulator.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#187 Created Rock Paper Scissor Game Python
  Python Codes/rock_paper.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#188 Added program to convert kilometres to miles
  Python Codes/kilometres_to_miles.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#189 Added a tool that helps understanding hamming code
  CONTRIBUTING.md
  Python Codes/hamming.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#190 A pdf or a docx file to speech convertor
  Python Codes/texttospeech.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#191 Password Generator
  CONTRIBUTING.md
  Python Codes/PasswordGenerator_pawarspeaks.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#194 Create couting_sort.py
  Python Codes/couting_sort.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#195 Rock paper scissor_
  Rock paper scissor_
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#197 Digital Clock Using Python
  Python Codes/Digital_Clock_with_python.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#198 Create Logistic Regression Project
  Fake-Advertising_Logistic_Regression.ipynb
  advertising.csv
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#199 copy contents of one file to another.py
  python/copy contents of one file to another.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#200 code for handtracker using open_cv
  handtracker.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#201 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#202 pacman
  Python Codes/pacman
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted
